version: "3.8"

services:
  mysqldb:
    image: mysql:latest
    volumes:
      - /scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=pfm_db
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    networks:
      - app-network
  app:
    depends_on:
      - mysqldb
    build: .
    restart: on-failure
    ports:
      - "8081:8081"
    networks:
      - app-network

networks:
  app-network: